source "https://rubygems.org"

gem "rails", "3.2.22.4"

gem "sqlite3"

gem "suture", :path => "../.."

gem "minitest", :group => :test

# 1.8.7 support
gem "rake", "~> 10.0"
gem "i18n", "~> 0.9.5"
gem "rack-cache", "~> 1.2.0"
