source 'https://rubygems.org'

gem 'rails', '3.2.22.4'

# for CRuby, Rubinius, including Windows and RubyInstaller
gem "sqlite3", :platform => [:ruby, :mswin, :mingw]

# for JRuby
gem "activerecord-jdbcsqlite3-adapter", :platform => :jruby

gem 'suture', :path => '../..'

gem 'minitest', :group => :test

# 1.8.7 support
gem 'rake', '~> 10.0'
gem 'i18n', '~> 0.6.0'
gem 'rack-cache', '~> 1.2.0'

