#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

RailsApp::Application.load_tasks

require "rake/testtask"
Rake::TestTask.new(:suture) do |t|
  t.libs << "lib"
  t.libs << "config"
  t.libs << "app"
  t.libs << "test"
  t.test_files = FileList['test/suture/**/*_test.rb']
end
